---
title: "Ibadan wet season data"
output: powerpoint_presentation
date: "2024-04-02"
---

```{r setup, include=FALSE, }
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
                      message = FALSE, fig.width= 12, fig.height= 8)
```

## Desriptive Statistics 

Slide deck provides a detailed description of the Ibadan wet season data. The data was collected from over 3000 households and has a total of over 6000 individuals tested for rdt.

## Wards were the data was collected 

- Agugu
- Bashorun
- Challenge
- Ologuneru

## The demographic breakdown of the wet season data in Ibadan

```{r cars, echo = F}
source("~/urban_malaria/cross_sectional_survey_data_cleaning/load_paths.R", echo = F)

malaria_cases <- read.csv(file.path(cleaned_data_path, metropolis_name,"ibadan_enviromental_covariates_coded.csv"))


newdat <- malaria_cases %>%
  # select(settlement_type_new, Ward, overgrown_vegetation) %>% 
  group_by(gender, Ward, agebin) %>% 
  summarise(value = sum(rdt_test_result, na.rm = T ),
            total = n(), 
            tpr = value/total)%>% 
  group_by() %>% 
  group_by(agebin, Ward) %>%
  # mutate(plot_position = cumsum(total) - total)
  mutate(plot_position = ifelse(gender == "Female", sum(total), 0))

ggplot(newdat, aes(fill=gender, y = total, x= agebin)) + 
  geom_bar(position="stack", stat="identity")+
  geom_text(aes(x = agebin, y = plot_position, label = total), color = "black",
            size = 3.5, size = 3.5, nudge_y = 10) +
  facet_wrap(~ Ward, ncol = 2)+
  scale_fill_manual(values = c("#fbb4ae", "#b3cde3")) +
  theme_minimal() +
  theme(panel.background = element_blank(),
        legend.title = element_blank(),
        text = element_text(size = 18), 
        legend.position = "bottom")

```

## Variable analysis 

```{r pressure}
plot(pressure)
```

